# Generated by Django 5.0.2 on 2024-03-10 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('expense', 'expense'), ('income', 'income')], max_length=50)),
                ('category', models.CharField(choices=[('miscellaneous', 'miscellaneous'), ('food', 'food'), ('shopping', 'shopping'), ('rent', 'rent'), ('fuel', 'fuel')], max_length=60)),
                ('amount', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
